### ISSUE TITLE
2.1.2 Showing up as 2.1.1 and not starting

### ISSUE THREAD

**Issue by LoJoSho** [Tutorialwork/WebApply#5]
I just got WebApply and downloaded 2.1.2. I then uploaded it and all. I opened it up to be greeted with https://i.gyazo.com/dd80d4e1ecbea7d6062e3981d646ebc1.png

I tried reinstalled and everything.

Folder with all the files: https://i.gyazo.com/4374d1f5476da9b639db4681ec2e0c69.png

**Comment by Tutorialwork** [comment]
Thanks for your bug report I fix it.
